version: "2"
services:
  app_elisabeth:
    build: .
    links:
      - db_elisabeth
    ports:
      - "8050:5000"
  db_elisabeth:
    image: mysql:5.7
    ports:
      - "34000:3306"
    environment:
      MYSQL_DATABASE: tst_uas
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro